apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: l7t84
rendezvousIP: 192.168.56.100
hosts:
  - hostname: master-0
    role: master
    interfaces:
      - name: ens192
        macAddress: 00:50:56:00:01:00
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:00:01:00
          ipv4:
            enabled: true
            address:
              - ip: 192.168.56.100
                prefix-length: 24 
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: ens192
            table-id: 254
  - hostname: master-1
    role: master
    interfaces:
      - name: ens192
        macAddress: 00:50:56:00:01:01
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:00:01:01
          ipv4:
            enabled: true
            address:
              - ip: 192.168.56.101
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: ens192
            table-id: 254
  - hostname: master-2
    role: master
    interfaces:
      - name: ens192
        macAddress: 00:50:56:00:01:02
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:00:01:02
          ipv4:
            enabled: true
            address:
              - ip: 192.168.56.102
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: ens192
            table-id: 254
  - hostname: worker-0
    role: worker
    interfaces:
      - name: ens192
        macAddress: 00:50:56:00:02:00 
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:00:02:00
          ipv4:
            enabled: true
            address:
              - ip: 192.168.56.200
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: ens192
            table-id: 254
  - hostname: worker-1
    role: worker
    interfaces:
      - name: ens192
        macAddress: 00:50:56:00:02:01
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:00:02:01
          ipv4:
            enabled: true
            address:
              - ip: 192.168.56.201
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: ens192
            table-id: 254