---
# defaults file for dns

service: dns
package:
  - bin
  - bind-utils
# this cluster-domain variable is a combination of the cluster name and cluster base domain
cluster-domain: 'cluster-domain.com'
ip_addr_segment_3: 0

