---
# tasks file for dns

- name: Install required software packages
  ansible.builtin.yum:
    name: "{{ package }}"
    state: present

- name: Open firewallD services
  ansible.posix.firewalld:
    service: "{{ service }}"
    permanent: yes
    immediate: yes
    state: enabled

- name: Configure reverse domain DNS file
  ansible.builtin.template:
    src: 168.192.in-addr.arpa.j2
    dest: "/var/named/{{  ip_addr_segment_3 }}.168.192.in-addr.arpa"

- name: Configure domain DNS file
  ansible.builtin.template:
    src: clusterdomain.zone.j2
    dest: "/var/named/clusterdomain.zone"

- name: Configure named main config
  ansible.builtin.template:
    src: named.conf.j2
    dest: "/etc/named.conf"

- name: Enable named
  ansible.builtin.service:
    name: named
    state: started
    enabled: true

- name: Configure resolv.conf
  ansible.builtin.copy:
    content: |
      search {{ clusterdomain }}
      nameserver 192.168.{{  ip_addr_segment_3 }}.10
    dest: /etc/resolv.conf