---
# tasks file for dns
- name: Open firewallD services
  ansible.posix.firewalld:
    service: "{{ service }}"
    permanent: yes
    immediate: yes
    state: enabled

- name: Install required software packages
  ansible.builtin.yum:
    name: "{{ package }}"
    state: present

- name: Configure reverse domain DNS file
  ansible.builtin.template:
    src: 168.192.in-addr.arpa.j2
    dest: "/var/named/{{ hostname_output.stdout }}.168.192.in-addr.arpa"

- name: Configure domain DNS file
  ansible.builtin.template:
    src: dynamic.opentlc.com.zone.j2
    dest: "/var/named/dynamic.opentlc.com.zone"

- name: Configure named main config
  ansible.builtin.template:
    src: named.conf.j2
    dest: "/etc/named.conf"

- name: Enable named
  ansible.builtin.service:
    name: named
    state: started
    enabled: true

- name: Configure resolv.conf
  ansible.builtin.copy:
    content: |
      search {{ guid }}.dynamic.opentlc.com
      nameserver 192.168.{{ hostname_output.stdout }}.10
    dest: /etc/resolv.conf